models:
  arima:
    look_back_window_size: 520
  exponential_smoothing:
    look_back_window_size: 780
  moving_average_recursive:
    look_back_window_size: 780
  prophet:
    look_back_window_size: 520
  simple_regression_net:
    look_back_window_size: 25
  recurrent_regression_net:
    look_back_window_size: 20
  LGBMRegressor:
    look_back_window_size: -1
  XGBRegressor:
    look_back_window_size: -1