stages:
  prepare:
    cmd: python prepare.py
    deps:
      - prepare.py
      - params.yaml
      - ../../config/data_config.yaml
    params:
      - start_date
      - end_date
    outs:
      - ../../data/main.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - ../../data/main.csv
      - ../../config/model_config.yaml
    outs:
      - ../../ckpts/main
  test:
    cmd: python test.py
    deps:
      - test.py
      - ../../ckpts/main
    outs:
      - ../../results/test_performance.csv
      - ../../results/test_predictions.csv
      - ../../results/test_ranked.csv
  forecast:
    cmd: python forecast.py
    deps:
      - forecast.py
      - ../../results/test_ranked.csv
    outs:
      - ../../ckpts/prod
      - ../../results/forecast.csv
  recommend:
    cmd: python recommend.py
    deps:
      - recommend.py
      - ../../results/forecast.csv
    outs:
      - ../../results/recommendation.json