stages:
  prepare:
    cmd: python prepare.py
    deps:
      - prepare.py
      - ../../config/data.yaml
    params:
      - prepare_params.yaml:
    outs:
      - ../../data/main.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - ../../data/main.csv
      - ../../config/models.yaml
    outs:
      - ../../ckpts/main
  test:
    cmd: python test.py
    deps:
      - test.py
      - ../../data/main.csv
      - ../../ckpts/main
    outs:
      - ../../results/test_metrics.csv
      - ../../results/test_predictions.csv
      - ../../results/test_ranked.csv
    metrics:
      - ../../results/test_metrics.json:
          cache: false
  forecast:
    cmd: python forecast.py
    deps:
      - forecast.py
      - ../../results/test_ranked.csv
    outs:
      - ../../ckpts/prod
      - ../../results/forecast.csv
  recommend:
    cmd: python recommend.py
    deps:
      - recommend.py
      - ../../results/forecast.csv
    metrics:
      - ../../results/recommendation.json:
          cache: false
